version: "3"

volumes:
  data:
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
      - target: 5432
    volumes:
      - data:/var/lib/postgresql
    expose:
      - 5432:5432

  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
      - target: 6379
  ipfs:
    image: ipfs/go-ipfs:latest
    command:
      - daemon
      - --migrate=true
      - --mount
      - --routing=dhtclient
      - --enable-namesys-pubsub
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse

    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata

    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001

    expose:
      - 8080:8080
      - 4001:4001
      - 5001:5001

    volumes:
      - ./data/ipfs:/ipfsdata
      - /etc/fuse.conf:/etc/fuse.conf:ro
      - ./data/ipfs:/data/ipfs
      - ./data/export:/export
