volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  nuclei_backend:
    # image: ronnytec/nuclei:latest
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
        - 8080:8080
    user: root
    privileged: true

    
  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8081:8081