volumes:
  data:

services:
  postgres:
    image: stellirin/postgres-windows
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  nuclei_backend:
    # image: ronnytec/nuclei:latest
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
        - 8000:8000
    user: root
    privileged: true

    
  redis-server:
    image: redis:3.2-windowsservercore
    ports:
      - 6379:6379