volumes:
  data:
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  redis-server:
    image: redis:latest
    ports:
      - 6379:6379

  ipfs:
    image: ipfs/go-ipfs:latest
    command: 
      - daemon 
      - --migrate=true 
      - --mount
      - --routing=dhtclient
      - --enable-namesys-pubsub
    privileged: true    # not needed in theory, adding this makes no difference though
    cap_add:
        - SYS_ADMIN
    security_opt:
        - apparmor:unconfined
    devices:
        - /dev/fuse:/dev/fuse
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    ports:
        - 8080:8080   # public gateway
        - 4001:4001   # public swarm UDP
        - 5001:5001   # private API
    volumes:
        - ./data/ipfs:/ipfsdata
        - /etc/fuse.conf:/etc/fuse.conf:ro
        - ./data/ipfs:/data/ipfs
        - ./data/export:/export      