apiVersion: v1
kind: Service
metadata:
  name: nuclei
  labels:
    app: nuclei
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
      protocol: TCP
      
  selector:
    app: nuclei
